### PR TITLE
improve listen

### PR DESCRIPTION
**Pull request by moodymudskipper**
@jrosell I reworked your draft into something that worked for me. It still needs some love re error handling and flexibility re browsers but on my mac with chrome it works fantastic. Could you try it ? If you don't use a Mac it'll be a miracle if it works out of the box.

### CODE REVIEW

**Comment by jrosell** [comment]
Sorry I couldn't check it today.

**Comment by moodymudskipper** [comment]
No rush at all, I prefer to merge it early to work comfortably on top of it, the package doesn't have many (any?) users yet so I don't really mind pushing half broken things for now. I hope stabilise and straighten things up in the coming weeks.

**Comment by jrosell** [comment]
Using Ubuntu with GPU enabled laptop I get this:


> library(ask)
> listen()
Loading required package: shiny

Listening on http://127.0.0.1:7139
[530651:530651:0908/000041.243731:ERROR:service_worker_task_queue.cc(239)] DidStartWorkerFail blaaajhemilngeeffpbfkdjjoefldkok: 5
[530651:530651:0908/000041.366159:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[530651:530651:0908/000041.415930:ERROR:service_worker_task_queue.cc(239)] DidStartWorkerFail blaaajhemilngeeffpbfkdjjoefldkok: 5
Created TensorFlow Lite XNNPACK delegate for CPU.
You asked:
how are you
[1] "how are you"
[530696:530702:0908/000053.807879:ERROR:chunked_data_pipe_upload_data_stream.cc(218)] OnSizeReceived failed with Error: -2
[530696:530702:0908/000101.834366:ERROR:chunked_data_pipe_upload_data_stream.cc(218)] OnSizeReceived failed with Error: -2
[530696:530702:0908/000109.857949:ERROR:chunked_data_pipe_upload_data_stream.cc(218)] OnSizeReceived failed with Error: -2
[530651:530651:0908/000111.370821:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=512
[530651:530651:0908/000111.684421:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=139
[530651:530651:0908/000111.924267:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=139
[531421:531464:0908/000112.041587:ERROR:x11_software_bitmap_presenter.cc(145)] XGetWindowAttributes failed for window 88080388
[530725:7:0908/000112.042463:ERROR:command_buffer_proxy_impl.cc(132)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#58 is a dynamic-sized tensor).
[530696:530702:0908/000117.890778:ERROR:chunked_data_pipe_upload_data_stream.cc(218)] OnSizeReceived failed with Error: -2
[530696:530702:0908/000125.918134:ERROR:chunked_data_pipe_upload_data_stream.cc(218)] OnSizeReceived failed with Error: -2
[530696:530702:0908/000204.849216:ERROR:chunked_data_pipe_upload_data_stream.cc(218)] OnSizeReceived failed with Error: -2

**Comment by moodymudskipper** [comment]
Thanks for trying it!

I tweaked the code and we now have : 

```
open_chrome_linux <- function(url) {
  command <- sprintf('google-chrome --disable-gpu --app="%s"', url)
  system(command)
}
```

Can you download the last version dev version and try again ?
And if it doesn't can you try `system('google-chrome --disable-gpu --app="https://www.google.com"')` ?

**Comment by jrosell** [comment]
I guess you already know, but I can confirm it's working on Linux on Chrome. Thanks.

**Pull request merged**
